name: Main CI CD

on:
  push:
    branches: [ main ]

jobs:
  re-build:
    strategy:
      matrix:
        runner-os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.runner-os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore cp_tiltswitch_hidromas/TiltSwitchSystem.sln
    - name: Build
      run: dotnet build cp_tiltswitch_hidromas/TiltSwitchSystem.sln -c Release --no-restore
   
      
  
